### ISSUE TITLE
Parallel Coordinates - Variable Filtering Not Working

### ISSUE THREAD

**Issue by ryanhausen** [comet-ml/issue-tracking#287]
Filtering on a single axis correctly filters experiments as visible/not visible. Filtering on an additional axis marks all experiments not visible. 

![examples](https://media.giphy.com/media/ckHNWhrI72qwG89DOM/giphy.gif)

**Comment by gidim** [comment]
Thanks for reporting. Looking into this

**Comment by Camru** [comment]
Hey, this is issue should be fixed now. Thanks for reporting.

**Comment by ryanhausen** [comment]
The issue is still occurring. Is there something specific to my project that perhaps is causing this behavior? 

https://www.comet.ml/kspa-subaru-hsc/cbottrell-subaru-hsc/view/BcelRvnEkXjptYTnWYCYif0O1

**Comment by gidim** [comment]
Yesterday’s deploy introduced a new bug that we didn’t anticipate. We rolled back to a previous version and plan on pushing a full fix tomorrow morning. Thanks for your patience

**Comment by ryanhausen** [comment]
No worries. I appreciate your work. I was just following up. Thanks again!
