### ISSUE TITLE
ContextualVersionConflict in jupyter when importing "from comet_ml import Experiment"

### ISSUE THREAD

**Issue by thomasjhuang** [comet-ml/issue-tracking#315]
I'm running into an issue in python 3.7 where importing comet results in this ContextualVersionConflict with json schema being involved somehow. Does this mean that my version of jsonschema is too old or too new?

`---------------------------------------------------------------------------
ContextualVersionConflict                 Traceback (most recent call last)
<ipython-input-346-7ecc4fcf4d92> in <module>
----> 1 from comet_ml import Experiment

/usr/local/lib/python3.7/site-packages/comet_ml/__init__.py in <module>
     73     "Histogram",
     74 ]
---> 75 __version__ = get_comet_version()
     76 
     77 LOGGER = logging.getLogger(__name__)

/usr/local/lib/python3.7/site-packages/comet_ml/utils.py in get_comet_version()
    750     # type: () -> str
    751     try:
--> 752         return get_distribution("comet_ml").version
    753     except DistributionNotFound:
    754         return "Please install comet with `pip install comet_ml`"

/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py in get_distribution(dist)
    479         dist = Requirement.parse(dist)
    480     if isinstance(dist, Requirement):
--> 481         dist = get_provider(dist)
    482     if not isinstance(dist, Distribution):
    483         raise TypeError("Expected string, Requirement, or Distribution", dist)

/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py in get_provider(moduleOrReq)
    355     """Return an IResourceProvider for the named module or requirement"""
    356     if isinstance(moduleOrReq, Requirement):
--> 357         return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
    358     try:
    359         module = sys.modules[moduleOrReq]

/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py in require(self, *requirements)
    898         included, even if they were already activated in this working set.
    899         """
--> 900         needed = self.resolve(parse_requirements(requirements))
    901 
    902         for dist in needed:

/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py in resolve(self, requirements, env, installer, replace_conflicting, extras)
    789                 # Oops, the "best" so far conflicts with a dependency
    790                 dependent_req = required_by[req]
--> 791                 raise VersionConflict(dist, req).with_context(dependent_req)
    792 
    793             # push the new requirements onto the stack

ContextualVersionConflict: (jsonschema 3.1.1 (/usr/local/lib/python3.7/site-packages), Requirement.parse('jsonschema<3.1.0,>=2.6.0'), {'comet-ml'})`

**Comment by dsblank** [comment]
How did you install comet_ml?

**Comment by thomasjhuang** [comment]
I did, but after reinstalling this issue went away. Thanks.

**Comment by steveazzolin** [comment]
I am running on the same issue:

`ContextualVersionConflict: (jsonschema 3.2.0 (/opt/conda/lib/python3.6/site-packages), Requirement.parse('jsonschema<3.1.0,>=2.6.0'), {'comet-ml'})`

Running on Kaggle notebook.
At the top of the cell I run this:
`!pip install jsonschema==3.0.1 comet_ml`
I tried to install `jsonschema==3.0.1` to solve the issue (default is 3.2) but did't work

**Comment by te-adm** [comment]
Looks like comet-ml is incompatible with all official AWS deep learning AMIs because of this.

**Comment by dsblank** [comment]
@steveazzolin Did you find a workaround?

**Comment by steveazzolin** [comment]
No, actually I gave up

**Comment by Nimrod007** [comment]
this was fixed in `comet-ml 3.1.8`

**Comment by kushalarora** [comment]
I am still getting this issue in version 3.1.8 with Google Colab, reverting to 3.0.2 fixed it.

**Comment by Nimrod007** [comment]
@Lothiraldan can you verify Google Colab pip install

**Comment by kushalarora** [comment]
I basically did pip install comet_ml. This succeeded but when I imported Experiment from Comet_ml it crashed. Does that answer your question?

This is my current setup. The one that failed is just the same but without specifying the comet_ml's version .
```
try:
    from comet_ml import API, APIExperiment
    import comet_ml
except Exception as e: 
    !pip install comet_ml==3.0.2
    from comet_ml import API, APIExperiment
    import comet_ml
```

**Comment by Nimrod007** [comment]
Thanks @kushalarora will update here once resolved

**Comment by kushalarora** [comment]
Thanks @Nimrod007. Btw, thanks for this amazing product. I really love comet_ml. :)

**Comment by Lothiraldan** [comment]
@kushalarora I reproduced the issue with Google Colab, one of our dependency `typing_extensions` is updated during the installation of the Comet Python SDK. But the chainer module requires an older version hence the conflict.

If you don't need to use chainer, you can safely restart the runtime by clicking on `Runtime` > `Restart runtime` of your notebook and you should be able to use the latest Comet Python SDK version. I would recommend restarting the runtime when you install / update your packages to avoid any kind of weird conflict like that.

We will investigate if we can support that old version of `typing-extensions` but the default versions of dependencies are pretty old on Google Colab.

**Comment by dsblank** [comment]
@kushalarora I believe that this issue has been fixed in recent versions of comet_ml. Thanks for the kind words, and reporting the issue!
