### ISSUE TITLE
Built-in line chart not working correctly on report

### ISSUE THREAD

**Issue by george-gca** [comet-ml/issue-tracking#399]
Using a built-in line chart, it currently displays the wrong values in the report

![image](https://user-images.githubusercontent.com/31376482/109538305-aebd6000-7a9e-11eb-8c4b-46fde0ab5139.png)

but it shows the correct values in the preview, when I click edit

![image](https://user-images.githubusercontent.com/31376482/109538525-f217ce80-7a9e-11eb-93f3-7d21986af096.png)

**Comment by dsblank** [comment]
Looking into this...

**Comment by dsblank** [comment]
@george-gca Can you provide (publically or privately) a link to the report?

**Comment by george-gca** [comment]
How can I send you privately? I tried to generate the same error for another report, but couldn't.

**Comment by dsblank** [comment]
I'm doug@comet.ml

**Comment by george-gca** [comment]
I was actually able to replicate the bug in one of my public projects [here](https://www.comet.ml/george-gca/super-resolution-experiments/reports/test-report). It happens when I create a set of panels, then duplicate them and just change the metric displayed in all plots. Watch the first plots, then go down the report and come back to the first plots. It will display the second set of plots in the first one.

**Comment by dsblank** [comment]
Thank you for the replication steps! We're now looking into this.

**Comment by dsblank** [comment]
We've identified the issue, and are testing the fix.

**Comment by dsblank** [comment]
This should be fixed now.

**Comment by george-gca** [comment]
@dsblank it is not fixed. You can see this in the public project I posted early. Look at the y axis of the first group of plots (0 to 1). Go down to the second group (between 20 to 30), then look back at the first group.

**Comment by george-gca** [comment]
Moment 1
![image](https://user-images.githubusercontent.com/31376482/113902373-308f6000-97a6-11eb-99f4-b2899658069f.png)

Moment 2
![image](https://user-images.githubusercontent.com/31376482/113902430-3f761280-97a6-11eb-845c-fbf7d95ad1c6.png)

**Comment by dsblank** [comment]
I don't see what you are showing, so it has either been fixed, or there is something else about your setup that isn't working. If you still see the above, can you post your browser and os versions? Thanks!

**Comment by george-gca** [comment]
Apparently, now it is fixed. I haven't changed the public project since that time.

**Comment by dsblank** [comment]
Thanks for checking and reporting back!
